# Generated by Django 4.0.1 on 2022-05-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
