# Generated by Django 4.0.1 on 2022-04-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volute',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('num_code', models.IntegerField()),
                ('char_code', models.CharField(max_length=10)),
                ('nominal', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('previous', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='car_photos',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
    ]
