# Generated by Django 4.0.1 on 2022-04-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_volute_alter_car_photos_car'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volute',
            new_name='Valute',
        ),
    ]
