# Generated by Django 4.0.3 on 2022-04-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
